version: 1.2.{build}.0
shallow_clone: true
assembly_info:
  patch: true
  file: '**\Assembly*Info.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  project: src/Spring2.Core.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test: off
  
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

artifacts:
  - path: '**\Spring2*.nupkg' # find all NuGet packages recursively
